Goodreads:
  APP_KEY: 'cf2Z3socJtT9qnlbjxTNw'
  APP_SECRET:  '1pSjMkE3tgrHmXdfT3wgpk7vFdYUsdU19t4NoyBg1BA'
  OAUTH_TOKEN : '1nApzFhQPdb9gFox9llDKw'
  OAUTH_SECRET : 'bP8k8IK0kHRnqOlVXQKWa4xzvDqBvv7FhO4Pq5m3DI'
