#!/usr/bin/env python
import sys
import argparse
import yaml

'''
This is a executable python file, it should provide a shell API for operations regarding blog exporting features
'''
def main():

    DESCRIPTION='''
        This script will give serve as an command line interface for the library here developed. It will enable you, in a quick way,
        to update your goodread account and export data from your Cybook into the goodread platform.
    '''


    try:
        parser = argparse.ArgumentParser(description=DESCRIPTION,formatter_class=argparse.RawTextHelpFormatter)

        parser.add_argument('-c','--configs',
            help='''
            The config file with the needed information. It will hold goodread app keys as well the path for your cybook database as well
            ''')

        args = parser.parse_args()
        CONFIGS=None

        if args.configs != None:
            with open(args.configs,'r') as f:
                CONFIGS = yaml.load(f)
                print CONFIGS

    except Exception as ex:
        print ex.message
        sys.exit(2)

if __name__ == "__main__":
    main()
